# Generated by Django 3.1.4 on 2020-12-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxapp', '0002_auto_20201208_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_tax', models.IntegerField()),
                ('resident_tax', models.IntegerField()),
                ('health_insurance_tax', models.IntegerField()),
                ('max_housetown_tax', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='taxmodel',
            old_name='income_tax',
            new_name='annual_income',
        ),
        migrations.RenameField(
            model_name='taxmodel',
            old_name='health_insurance_tax',
            new_name='care_fee',
        ),
        migrations.RenameField(
            model_name='taxmodel',
            old_name='resident_tax',
            new_name='insurance_fee',
        ),
        migrations.RenameField(
            model_name='taxmodel',
            old_name='max_housetown_tax',
            new_name='life_fee',
        ),
        migrations.AddField(
            model_name='taxmodel',
            name='basic_yes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxmodel',
            name='blue_yes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxmodel',
            name='pension_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
